name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Instalar dependências
        run: npm ci

      - name: Build de produção
        run: npm run build:prod

      - name: Publicar pacote
        run: npm publish --access restricted
        working-directory: dist/commons-material
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
